### ISSUE TITLE
Android app will crash, when LNURLw doesn't have enough resources

### ISSUE THREAD

**Issue by theerror** [michaelWuensch/BitBanana#50]
## Description

When there is LNURLw what allow withdrawal more, then it's actually placed on wallet, instead of error and failed payment, application will completely crash. 

## Expected Behavior

Error about failed payment.

## Actual Behavior

App crashes completely. 

## Possible Fix

Handle error of failed payment. 

## Steps to Reproduce

1. On LNBits create LNURw and fund wallet some sats, but less then maximal allowed amount
2. Try withdraw some funds, lower than limit, but higher then actual funds available using Android app 
3. App will crash. 

## Context

Annoying :)

## Your Environment

Mi 10T Pro, Android 12 (MIUI 13.0.8)

- BitBanana version: _(0.6.6-beta)_
- Android version: _(12 SKQ1.2211006)_
- Device: _(Mi 10T Pro)_
- LND Version: _(v0.16.4-beta)_
- LNBits Version: _(0.10.10)_

**Comment by michaelWuensch** [comment]
@theerror 
Thanks for reporting the issue.
I was not aware of it. I'll see what I can do!

**Comment by michaelWuensch** [comment]
@theerror 
I found the issue. Actually LNBits is not following the LNURL Spec correctly. 
See the Issue that I opened here: https://github.com/lnbits/lnbits/issues/1953 

Still it should of course not crash. I fixed the crash now (https://github.com/michaelWuensch/BitBanana/commit/00b98e70a17de0beeacb8d698b6fef896ec3349a) but due to the incorrect format of the returned error, it doesn't look that pretty. Once LNBits fixed their LNURLw implementation, the error message should look fine.

The fix will be in the next version, that will drop quite soon!

This is how it looks now:
![img](https://github.com/michaelWuensch/BitBanana/assets/15313630/0651c0bb-2d9f-4e6a-aded-3595efdacd90)
